### ISSUE TITLE
Can you send me datasets you have divided? 

### ISSUE THREAD

**Issue by longmalongma** [ace19-dev/image-retrieval-tf#3]
Can you send me datasets you have divided to my email? I can not generate files according to your code,such as train.record,query.record,and so on.my email is that :1442342449@qq.com

**Comment by ace19-dev** [comment]
I am sorry to tell you i dont have. you can download datasets and make .record file from source in thie repo. good luck.

**Comment by longmalongma** [comment]
I think your code is incomplete.I wait after someone run your code successfully,I will try to it again.Than you again.




------------------ 原始邮件 ------------------
发件人: "Sean Kim"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 中午11:59
收件人: "ace19-dev/image-retrieval-tf"<image-retrieval-tf@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ace19-dev/image-retrieval-tf] Can you send me datasets you havedivided?  (#3)




I am sorry to tell you i dont have. you can download datasets and make .record file from source in thie repo. good luck.

**Comment by ace19-dev** [comment]
You seem to try to eat without using your hands. Do I have to explain everything? Or did you test it while debugging in detail? I learned and posted the results to this repository. Before you talk about it, think about how much you tested and looked.

**Comment by longmalongma** [comment]
I am sorry,I'm in too much of a hurry. I'll take a closer look




------------------ 原始邮件 ------------------
发件人: "Sean Kim"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 中午12:30
收件人: "ace19-dev/image-retrieval-tf"<image-retrieval-tf@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ace19-dev/image-retrieval-tf] Can you send me datasets you havedivided?  (#3)




You seem to try to eat without using your hands. Do I have to explain everything? Or did you test it while debugging in detail? I learned and posted the results to this repository. Before you talk about it, think about how much you tested and looked.
